- type: entity
  parent: BaseItem
  id: WeaponLaserWH40KEnergy
  abstract: true
  components:
  - type: AmmoCounter
  - type: Gun
    fireRate: 3
    selectedMode: SemiAuto
    availableModes:
    - FullAuto
    - SemiAuto
    soundGunshot:
      path: /Audio/_WH40K/Weapons/Guns/Gunshots/lasgunpew.ogg
  - type: MagazineAmmoProvider
  - type: ItemSlots
    slots:
      gun_magazine:
        name: Magazine
        startingItem: LasgunPowerCell
        insertSound: /Audio/Weapons/Guns/MagIn/batrifle_magin.ogg
        ejectSound: /Audio/Weapons/Guns/MagOut/batrifle_magout.ogg
        whitelist:
          tags:
            - LasgunPowerCell
  - type: Appearance
  - type: StaticPrice
    price: 500
  - type: ContainerContainer
    containers:
      gun_magazine: !type:ContainerSlot
  - type: Sprite
    sprite: _WH40K/Objects/Weapons/Guns/Battery/lasgun.rsi
    scale: 0.85,0.85
    layers:
      - state: base
        map: ["enum.GunVisualLayers.Base"]
      - state: mag-0
        map: ["enum.GunVisualLayers.Mag"]
  - type: Item
    sprite: _WH40K/Objects/Weapons/Guns/Battery/lasgun_in-hands.rsi
    size: Huge
    shape:
    - 0,0,4,1
  - type: MagazineVisuals
    magState: mag
    steps: 1
    zeroVisible: true
